apiVersion: v1
kind: Service
metadata:
  name: pipeline
  labels:
    app: pipeline
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8011
    protocol: TCP
    name: http
  selector:
    app: pipeline
status:
  loadBalancer: {}